#ifndef W3DLANGTABLA_H
#define W3DLANGTABLA_H

// GENERADO. No editar a mano: se regenera desde el diccionario (scratchpad/genlang.py).
//
// ORDENADA por el texto ingles en orden strcmp: T() la bisecta y ese orden es el invariante del que
// depende. El generador lo verifica antes de escribir este archivo.
//
// La clave es el propio ingles -> lo que no este aca sale en ingles, que es exactamente lo que se quiere.

struct W3dLangEntrada { const char* en; const char* es; const char* pt; };

static const W3dLangEntrada W3dLangTabla[] = {
    { "\" already exists. Do you want to replace it?", "\" ya existe. ¿Reemplazarlo?", "\" já existe. Deseja substituí-lo?" },
    { "(Esc to cancel)", "(Esc para cancelar)", "(Esc para cancelar)" },
    { "(coming soon)", "(próximamente)", "(em breve)" },
    { "(no properties yet)", "(sin propiedades aún)", "(sem propriedades ainda)" },
    { "3D Cursor", "Cursor 3D", "Cursor 3D" },
    { "3D Viewport", "Vista 3D", "Viewport 3D" },
    { ": baked", ": horneado", ": bakeado" },
    { "Abrir normal map", "Abrir Mapa de Normales", "Abrir Mapa de Normais" },
    { "Active", "Activo", "Ativo" },
    { "Active Camera", "Cámara Activa", "Câmera Ativa" },
    { "Active Element", "Elemento activo", "Elemento ativo" },
    { "Add", "Añadir", "Adicionar" },
    { "Add Circle", "Añadir Círculo", "Adicionar Círculo" },
    { "Add Color Layer", "Añadir Capa de Color", "Adicionar Camada de Cor" },
    { "Add Cone", "Añadir Cono", "Adicionar Cone" },
    { "Add Cube", "Añadir Cubo", "Adicionar Cubo" },
    { "Add Cylinder", "Añadir Cilindro", "Adicionar Cilindro" },
    { "Add Plane", "Añadir Plano", "Adicionar Plano" },
    { "Add UV Map", "Añadir Mapa UV", "Adicionar Mapa UV" },
    { "Add UV Sphere", "Añadir Esfera UV", "Adicionar Esfera UV" },
    { "Add Vertex Group", "Añadir Grupo de Vértices", "Adicionar Grupo de Vértices" },
    { "Affect Move", "Afectar Mover", "Afetar Mover" },
    { "Affect Rotate", "Afectar Rotar", "Afetar Rotacionar" },
    { "Affect Scale", "Afectar Escalar", "Afetar Escalar" },
    { "Aligned", "Alineada", "Alinhada" },
    { "All", "Todo", "Tudo" },
    { "All Transforms", "Todas las Transformaciones", "Todas as Transformações" },
    { "Alpha Preview", "Vista Alpha", "Prévia Alpha" },
    { "Ambient", "Ambiente", "Ambiente" },
    { "Angle", "Ángulo", "Ângulo" },
    { "Animation", "Animación", "Animação" },
    { "Animation rendered!", "¡Animación renderizada!", "Animação renderizada!" },
    { "Apply", "Aplicar", "Aplicar" },
    { "Apply Modifier", "Aplicar Modificador", "Aplicar Modificador" },
    { "Apply Modifiers", "Aplicar Modificadores", "Aplicar Modificadores" },
    { "Apply Transforms", "Aplicar Transformaciones", "Aplicar Transformações" },
    { "Apply: select mesh or armature object(s)", "Aplicar: selecciona malla(s) o esqueleto(s)", "Aplicar: selecione malha(s) ou armação(ões)" },
    { "Armature", "Esqueleto", "Armação" },
    { "Assign", "Asignar", "Atribuir" },
    { "At Center", "En el centro", "No centro" },
    { "At Cursor", "En el cursor", "No cursor" },
    { "Att Constant", "Att Constante", "Att Constante" },
    { "Att Linear", "Att Lineal", "Att Linear" },
    { "Att Quadratic", "Att Cuadrática", "Att Quadrática" },
    { "Auto (active part)", "Auto (parte activa)", "Auto (parte ativa)" },
    { "Auto Clamped", "Auto Limitada", "Auto Limitada" },
    { "Auto Merge", "Auto Fusionar", "Auto Mesclar" },
    { "Auto frame", "Auto encuadre", "Auto enquadre" },
    { "Automatic", "Automática", "Automática" },
    { "Axis", "Eje", "Eixo" },
    { "Axis Angle", "Ángulo de Eje", "Ângulo de Eixo" },
    { "Back", "Posterior", "Traseira" },
    { "Background", "Fondo", "Fundo" },
    { "Base Color", "Color Base", "Cor Base" },
    { "Blue", "Azul", "Azul" },
    { "Bones", "Huesos", "Ossos" },
    { "Boolean", "Booleano", "Booleano" },
    { "Bottom", "Inferior", "Inferior" },
    { "By Distance", "Por distancia", "Por distância" },
    { "Cache Animation", "Caché de Animación", "Cache de Animação" },
    { "Camera", "Cámara", "Câmera" },
    { "Cameras", "Cámaras", "Câmeras" },
    { "Cancel", "Cancelar", "Cancelar" },
    { "Cargar normal map", "Cargar Mapa de Normales", "Carregar Mapa de Normais" },
    { "Cargar textura (imagen)", "Cargar textura (imagen)", "Carregar textura (imagem)" },
    { "Center", "Centro", "Centro" },
    { "Circle", "Círculo", "Círculo" },
    { "Clear Keyframe", "Limpiar Keyframes", "Limpar Keyframes" },
    { "Clear Parent", "Desemparentar", "Desparentear" },
    { "Clear Parent Inverse", "Limpiar Inversa del Padre", "Limpar Inversa do Pai" },
    { "Clear Screen", "Limpiar Pantalla", "Limpar Tela" },
    { "Clear Seam", "Limpiar Costura", "Limpar Costura" },
    { "Clear Sharp", "Limpiar Afilado", "Limpar Aguda" },
    { "Clear Transform", "Limpiar Transformación", "Limpar Transformação" },
    { "Clear and Keep Transformation", "Limpiar y Mantener Transformación", "Limpar e Manter Transformação" },
    { "Clipping", "Recorte", "Recorte" },
    { "Closest", "Más Cercano", "Mais Próximo" },
    { "Collapse", "Colapsar", "Colapsar" },
    { "Collection", "Colección", "Coleção" },
    { "Color", "Color", "Cor" },
    { "Color Mode", "Modo de Color", "Modo de Cor" },
    { "Cone", "Cono", "Cone" },
    { "Constant", "Constante", "Constante" },
    { "Could not write config.ini", "No se pudo escribir config.ini", "Nao foi possivel gravar config.ini" },
    { "Cube", "Cubo", "Cubo" },
    { "Cube Projection", "Proyección de Cubo", "Projeção de Cubo" },
    { "Current Frame", "Frame Actual", "Frame Atual" },
    { "Cursor to Active", "Cursor al activo", "Cursor para o ativo" },
    { "Cursor to Center", "Cursor a Centro", "Cursor para Centro" },
    { "Cursor to Grid", "Cursor a la cuadrícula", "Cursor para a grade" },
    { "Cursor to Selected", "Cursor a lo seleccionado", "Cursor para o selecionado" },
    { "Cursor to Selection", "Cursor a Selección", "Cursor para Seleção" },
    { "Cursor to World Origin", "Cursor al origen del mundo", "Cursor para a origem do mundo" },
    { "Curves", "Curvas", "Curvas" },
    { "Custom Normal", "Normal Personalizada", "Normal Personalizada" },
    { "Cylinder", "Cilindro", "Cilindro" },
    { "Cylinder Projection", "Proyección de Cilindro", "Projeção de Cilindro" },
    { "Default Material", "Material por Defecto", "Material Padrão" },
    { "Delete", "Borrar", "Excluir" },
    { "Delete \"%s\"?", "¿Borrar \"%s\"?", "Excluir \"%s\"?" },
    { "Delete %d objects?", "¿Borrar %d objetos?", "Excluir %d objetos?" },
    { "Delete Edge Loops: select an edge loop first", "Borrar Edge Loops: selecciona un edge loop primero", "Excluir Edge Loops: selecione um edge loop primeiro" },
    { "Delete Keyframe", "Borrar Keyframe", "Excluir Keyframe" },
    { "Delete selected?", "¿Borrar lo seleccionado?", "Excluir a seleção?" },
    { "Depth", "Profundidad", "Profundidade" },
    { "Depth Test", "Test de Profundidad", "Teste de Profundidade" },
    { "Deselect", "Deseleccionar", "Desselecionar" },
    { "Diffuse", "Difuso", "Difuso" },
    { "Directional", "Direccional", "Direcional" },
    { "Display in Edit Mode", "Mostrar en Modo Edición", "Mostrar no Modo Edição" },
    { "Display in Viewport", "Mostrar en Viewport", "Mostrar na Viewport" },
    { "Duplicate", "Duplicar", "Duplicar" },
    { "Duplicate Linked", "Duplicar Vinculado", "Duplicar Vinculado" },
    { "Duplicate Objects", "Duplicar Objetos", "Duplicar Objetos" },
    { "Edge", "Arista", "Aresta" },
    { "Edge Center", "Centro de Arista", "Centro da Aresta" },
    { "Edge Loops", "Loops de Aristas", "Loops de Arestas" },
    { "Edges", "Aristas", "Arestas" },
    { "Edit Mode", "Modo Edición", "Modo Edição" },
    { "Elegir archivo", "Elegir Archivo", "Escolher Arquivo" },
    { "Emission", "Emisión", "Emissão" },
    { "Empty", "Vacío", "Vazio" },
    { "Enable", "Activar", "Ativar" },
    { "End", "Fin", "Fim" },
    { "End:%d", "Fin:%d", "Fim:%d" },
    { "Equirectangular (software)", "Equirectangular (software)", "Equirretangular (software)" },
    { "Error rendering animation", "Error al renderizar la animación", "Erro ao renderizar a animação" },
    { "Error: could not save the OBJ", "Error: no se pudo guardar el OBJ", "Erro: não foi possível salvar o OBJ" },
    { "Error: could not save the render", "Error: no se pudo guardar el render", "Erro: não foi possível salvar o render" },
    { "Esto modificara el vertex group y lo simplificara a 1 hueso por vertice (skinning mas rapido). Puede haber perdida de datos.", "Esto modificará el grupo de vértices y lo simplificará a 1 hueso por vértice (skinning más rápido). Puede haber pérdida de datos.", "Isto modificará o grupo de vértices e o simplificará para 1 osso por vértice (skinning mais rápido). Pode haver perda de dados." },
    { "Expand", "Expandir", "Expandir" },
    { "Export", "Exportar", "Exportar" },
    { "Export to...", "Exportar a...", "Exportar para..." },
    { "Extrude", "Extruir", "Extrudar" },
    { "Extrude Edges", "Extruir Aristas", "Extrudar Arestas" },
    { "Extrude Faces", "Extruir Caras", "Extrudar Faces" },
    { "Extrude Vertices", "Extruir Vértices", "Extrudar Vértices" },
    { "FBX export: not available yet", "Exportar FBX: aún no disponible", "Exportar FBX: ainda não disponível" },
    { "Face", "Cara", "Face" },
    { "Face Center", "Centro de cara", "Centro da face" },
    { "Face Nearest", "Cara más cercana", "Face mais próxima" },
    { "Face Normal", "Normal de Cara", "Normal de Face" },
    { "Face Project", "Proyectar en cara", "Projetar na face" },
    { "Faces", "Caras", "Faces" },
    { "Faces triangulated", "Caras trianguladas", "Faces trianguladas" },
    { "Factor", "Factor", "Fator" },
    { "File name", "Nombre de archivo", "Nome do arquivo" },
    { "Filtering", "Filtrado", "Filtragem" },
    { "Flip", "Voltear", "Virar" },
    { "Flip Normals", "Invertir Normales", "Inverter Normais" },
    { "Floor", "Piso", "Piso" },
    { "Follow Active Quads", "Seguir Quads Activos", "Seguir Quads Ativos" },
    { "Follow Active Quads: not implemented yet", "Seguir Quads Activos: aún no implementado", "Seguir Quads Ativos: ainda não implementado" },
    { "Frame Selected", "Encuadrar Selección", "Enquadrar Seleção" },
    { "Frame Skip", "Salto de Frames", "Salto de Frames" },
    { "Free", "Libre", "Livre" },
    { "Front", "Frontal", "Frontal" },
    { "GL Light", "Luz GL", "Luz GL" },
    { "Geometry to Origin", "Geometría al Origen", "Geometria para Origem" },
    { "Green", "Verde", "Verde" },
    { "Handle Type", "Tipo de Manija", "Tipo de Alça" },
    { "Height", "Alto", "Altura" },
    { "Hue", "Matiz", "Matiz" },
    { "Import FBX", "Importar FBX", "Importar FBX" },
    { "Import GLB", "Importar GLB", "Importar GLB" },
    { "Import OBJ", "Importar OBJ", "Importar OBJ" },
    { "Import glTF", "Importar glTF", "Importar glTF" },
    { "Imports", "Importar", "Importar" },
    { "Include Active", "Incluir Activo", "Incluir Ativo" },
    { "Include Edited", "Incluir Editado", "Incluir Editado" },
    { "Include Non-Edited", "Incluir No Editado", "Incluir Não Editado" },
    { "Individual Elements", "Elementos individuales", "Elementos individuais" },
    { "Individual Origins", "Orígenes individuales", "Origens individuais" },
    { "Insert Keyframe", "Insertar Keyframe", "Inserir Keyframe" },
    { "Inside", "Interior", "Interior" },
    { "Interpolation", "Interpolación", "Interpolação" },
    { "Interpolation Mode", "Modo de Interpolación", "Modo de Interpolação" },
    { "Invert", "Invertir", "Inverter" },
    { "Join", "Unir", "Juntar" },
    { "Join: no active mesh object", "Unir: no hay malla activa", "Juntar: não há malha ativa" },
    { "Join: select 2+ mesh objects (active is the target)", "Unir: selecciona 2+ mallas (la activa es el destino)", "Juntar: selecione 2+ malhas (a ativa é o destino)" },
    { "Joined into", "Unido en", "Unido em" },
    { "Left", "Izquierda", "Esquerda" },
    { "Left Handle X", "Manija Izq. X", "Alça Esq. X" },
    { "Levels Viewport", "Niveles Viewport", "Níveis Viewport" },
    { "Light", "Luz", "Luz" },
    { "Lighting", "Iluminación", "Iluminação" },
    { "Lights", "Luces", "Luzes" },
    { "Linear", "Lineal", "Linear" },
    { "Linked", "Vinculado", "Vinculado" },
    { "Load Texture", "Cargar Textura", "Carregar Textura" },
    { "Location", "Posición", "Posição" },
    { "Location X", "Posición X", "Posição X" },
    { "Lock Normals", "Bloquear normales", "Travar normais" },
    { "Lock Orbit", "Bloquear Órbita", "Travar Órbita" },
    { "Loop Cut and Slide", "Loop Cut y Deslizar", "Loop Cut e Deslizar" },
    { "Loop Cut: enter Edit Mode first", "Loop Cut: entra primero en Modo Edición", "Loop Cut: entre no Modo de Edição primeiro" },
    { "Loop Cut: move = slide, Enter to confirm, Esc = center", "Loop Cut: mover = deslizar, Enter confirma, Esc = centrar", "Loop Cut: mover = deslizar, Enter confirma, Esc = centralizar" },
    { "Loop Cut: no active edge (click an edge first)", "Loop Cut: sin arista activa (clic en una arista primero)", "Loop Cut: sem aresta ativa (clique em uma aresta primeiro)" },
    { "Loop Cut: no active face (click a face first)", "Loop Cut: sin cara activa (clic en una cara primero)", "Loop Cut: sem face ativa (clique em uma face primeiro)" },
    { "Loop Cut: scroll = number of cuts, Enter to confirm", "Loop Cut: rueda = cantidad de cortes, Enter confirma", "Loop Cut: roda = número de cortes, Enter confirma" },
    { "Loop Cut: select an edge (2 verts) or a quad (4 verts)", "Loop Cut: selecciona una arista (2 vért.) o un quad (4 vért.)", "Loop Cut: selecione uma aresta (2 vért.) ou um quad (4 vért.)" },
    { "Loop Cut: select the 4 vertices of one quad", "Loop Cut: selecciona los 4 vértices de un quad", "Loop Cut: selecione os 4 vértices de um quad" },
    { "Loop Cut: tap a yellow dot to pick the cut direction (or arrows + Enter)", "Loop Cut: toca un punto amarillo para elegir la dirección del corte (o flechas + Enter)", "Loop Cut: toque um ponto amarelo para escolher a direção do corte (ou setas + Enter)" },
    { "Loop Cut: the 2 selected vertices are not an edge", "Loop Cut: los 2 vértices seleccionados no forman una arista", "Loop Cut: os 2 vértices selecionados não formam uma aresta" },
    { "Loop Cut: the active face has no edges", "Loop Cut: la cara activa no tiene aristas", "Loop Cut: a face ativa não tem arestas" },
    { "Loop Cut: the active face is not a quad", "Loop Cut: la cara activa no es un quad", "Loop Cut: a face ativa não é um quad" },
    { "Loop Select", "Seleccionar Loop", "Selecionar Loop" },
    { "Loop Select (Edge Loop)", "Seleccionar Loop (Edge Loop)", "Selecionar Loop (Edge Loop)" },
    { "Loop Select (Edge Ring)", "Seleccionar Loop (Edge Ring)", "Selecionar Loop (Edge Ring)" },
    { "Loop Select: arrows = direction, Enter to confirm", "Loop Select: flechas = dirección, Enter para confirmar", "Loop Select: setas = direção, Enter para confirmar" },
    { "Loop Select: click an", "Loop Select: clic en una", "Loop Select: clique em uma" },
    { "Mark Seam", "Marcar Costura", "Marcar Costura" },
    { "Mark Sharp", "Marcar Afilado", "Marcar Aguda" },
    { "Material Preview", "Vista Material", "Prévia Material" },
    { "Maximize", "Maximizar", "Maximizar" },
    { "Median", "Mediana", "Mediana" },
    { "Median Point", "Punto medio", "Ponto médio" },
    { "Merge", "Fusionar", "Mesclar" },
    { "Merge Distance", "Distancia de Fusión", "Distância de Mesclagem" },
    { "Mesh", "Malla", "Malha" },
    { "Mesh Parts", "Partes de Malla", "Partes de Malha" },
    { "Minimize", "Minimizar", "Minimizar" },
    { "Mirror", "Espejo", "Espelho" },
    { "Mirror Object", "Objeto Espejo", "Objeto Espelho" },
    { "Mirror X", "Espejo X", "Espelho X" },
    { "Mirror Y", "Espejo Y", "Espelho Y" },
    { "Mirror Z", "Espejo Z", "Espelho Z" },
    { "Mode", "Modo", "Modo" },
    { "Modifier", "Modificador", "Modificador" },
    { "Modifier applied", "Modificador aplicado", "Modificador aplicado" },
    { "Modifiers", "Modificadores", "Modificadores" },
    { "Motion Trail", "Rastro de Movimiento", "Rastro de Movimento" },
    { "Move", "Mover", "Mover" },
    { "Move Down", "Bajar", "Descer" },
    { "Move Up", "Subir", "Subir" },
    { "Move: %d frames", "Mover: %d frames", "Mover: %d frames" },
    { "Move: %d frames, %.3f value%s", "Mover: %d frames, %.3f valor%s", "Mover: %d frames, %.3f valor%s" },
    { "Name", "Nombre", "Nome" },
    { "New", "Nuevo", "Novo" },
    { "New Animation", "Nueva Animación", "Nova Animação" },
    { "New Edge/Face from Vertices", "Nueva Arista/Cara desde Vértices", "Nova Aresta/Face dos Vértices" },
    { "New Material", "Nuevo Material", "Novo Material" },
    { "New Mesh Part", "Nueva Parte", "Nova Parte" },
    { "No", "No", "Não" },
    { "No Normal Map", "Sin Mapa de Normales", "Sem Mapa de Normais" },
    { "No Texture", "Sin Textura", "Sem Textura" },
    { "No active 3D viewport", "No hay vista 3D activa", "Nenhuma viewport 3D ativa" },
    { "None", "Ninguno", "Nenhum" },
    { "Normal Mapping", "Mapa de Normales", "Mapa de Normais" },
    { "Normal Size", "Tamaño de Normal", "Tamanho da Normal" },
    { "Normal View", "Vista Normal", "Vista Normal" },
    { "Normals", "Normales", "Normais" },
    { "Now click the second", "Ahora, segundo clic en", "Agora, segundo clique em" },
    { "Number of Cuts", "Número de Cortes", "Número de Cortes" },
    { "OBJ does not store the skeleton or animations: only the mesh will be exported (vertex groups, armature and clips will be lost). It will overwrite the file if it already exists. Continue?", "OBJ no guarda el esqueleto ni las animaciones: solo se exportará la malla (se perderán los grupos de vértices, el esqueleto y los clips). Sobrescribirá el archivo si ya existe. ¿Continuar?", "OBJ não armazena o esqueleto nem as animações: apenas a malha será exportada (grupos de vértices, armação e clipes serão perdidos). Vai sobrescrever o arquivo se já existir. Continuar?" },
    { "OBJ saved successfully!", "¡OBJ guardado correctamente!", "OBJ salvo com sucesso!" },
    { "Object", "Objeto", "Objeto" },
    { "Object (Keep Transform Without Inverse)", "Objeto (Mantener Transform. Sin Inversa)", "Objeto (Manter Transform. Sem Inversa)" },
    { "Object (Keep Transform)", "Objeto (Mantener Transform.)", "Objeto (Manter Transform.)" },
    { "Object (Without Inverse)", "Objeto (Sin Inversa)", "Objeto (Sem Inversa)" },
    { "Object Mode", "Modo Objeto", "Modo Objeto" },
    { "Object Transforms", "Transformaciones de Objeto", "Transformações do Objeto" },
    { "Objects", "Objetos", "Objetos" },
    { "Optimize Vertex Groups", "Optimizar Grupos de Vértices", "Otimizar Grupos de Vértices" },
    { "Orbit locked", "Órbita bloqueada", "Órbita bloqueada" },
    { "Orbit unlocked", "Órbita desbloqueada", "Órbita desbloqueada" },
    { "Orient", "Orient.", "Orient." },
    { "Origin to 3D Cursor", "Origen al Cursor 3D", "Origem para Cursor 3D" },
    { "Origin to Geometry", "Origen a Geometría", "Origem para Geometria" },
    { "Origins", "Orígenes", "Origens" },
    { "Overlays", "Superposiciones", "Sobreposições" },
    { "Parent", "Padre", "Pai" },
    { "Path", "Ruta", "Caminho" },
    { "Per-Corner", "Por Esquina", "Por Canto" },
    { "Per-Vertex", "Por Vértice", "Por Vértice" },
    { "Perspective/Ortho", "Perspectiva/Orto", "Perspectiva/Orto" },
    { "Pick Shortest Path", "Camino Más Corto", "Caminho Mais Curto" },
    { "Pick Shortest Path: click the first", "Camino más corto: clic inicial en", "Caminho mais curto: clique inicial em" },
    { "Plane", "Plano", "Plano" },
    { "Pose Mode", "Modo Pose", "Modo Pose" },
    { "Project from View", "Proyectar desde Vista", "Projetar da Vista" },
    { "Project from View (Bounds)", "Proyectar desde Vista (Límites)", "Projetar da Vista (Limites)" },
    { "Project from View: select faces first", "Proyectar desde Vista: selecciona caras primero", "Projetar da Vista: selecione faces primeiro" },
    { "Properties", "Propiedades", "Propriedades" },
    { "Quaternion (WXYZ)", "Cuaternión (WXYZ)", "Quaternion (WXYZ)" },
    { "Radius", "Radio", "Raio" },
    { "Radius 1", "Radio 1", "Raio 1" },
    { "Radius 2", "Radio 2", "Raio 2" },
    { "Recalculate Normals", "Recalcular Normales", "Recalcular Normais" },
    { "Red", "Rojo", "Vermelho" },
    { "Reference", "Referencia", "Referência" },
    { "Reflection", "Reflejo", "Reflexo" },
    { "Relationship Lines", "Líneas de Relación", "Linhas de Relação" },
    { "Remove", "Quitar", "Remover" },
    { "Rename", "Renombrar", "Renomear" },
    { "Rename Material", "Renombrar Material", "Renomear Material" },
    { "Render Animation", "Renderizar Animación", "Renderizar Animação" },
    { "Render Image", "Renderizar Imagen", "Renderizar Imagem" },
    { "Render Preview", "Vista Render", "Prévia Render" },
    { "Render saved!", "¡Render guardado!", "Render salvo!" },
    { "Render to...", "Renderizar en...", "Renderizar em..." },
    { "Rendering animation...", "Renderizando animación...", "Renderizando animação..." },
    { "Rendering...", "Renderizando...", "Renderizando..." },
    { "Repeat", "Repetir", "Repetir" },
    { "Repeat Texture", "Repetir Textura", "Repetir Textura" },
    { "Restart Whisk3D for this change to take effect", "Debes reiniciar Whisk3D para que este valor surta efecto", "Reinicie o Whisk3D para que esta alteracao tenha efeito" },
    { "Right", "Derecha", "Direita" },
    { "Right Handle X", "Manija Der. X", "Alça Dir. X" },
    { "Rings", "Anillos", "Anéis" },
    { "Rip", "Rasgar", "Rasgar" },
    { "Rip: mesh separated", "Rip: malla separada", "Rip: malha separada" },
    { "Rip: the selection does not separate the mesh", "Rip: la selección no separa la malla", "Rip: a seleção não separa a malha" },
    { "Rotate", "Rotar", "Rotacionar" },
    { "Rotate: %.1f deg  (pivot %s)", "Rotar: %.1f grados  (pivote %s)", "Rotacionar: %.1f graus  (pivô %s)" },
    { "Rotation", "Rotación", "Rotação" },
    { "Rotation W", "Rotación W", "Rotação W" },
    { "Rotation X", "Rotación X", "Rotação X" },
    { "Saturation", "Saturación", "Saturação" },
    { "Save Changes", "Guardar cambios", "Salvar alteracoes" },
    { "Scale", "Escalar", "Escalar" },
    { "Scale X", "Escala X", "Escala X" },
    { "Scale Y", "Escala Y", "Escala Y" },
    { "Scale Z", "Escala Z", "Escala Z" },
    { "Scale: %.2fx  (pivot %s)%s", "Escalar: %.2fx  (pivote %s)%s", "Escalar: %.2fx  (pivô %s)%s" },
    { "Scene", "Escena", "Cena" },
    { "Scenes", "Escenas", "Cenas" },
    { "Segments", "Segmentos", "Segmentos" },
    { "Select", "Seleccionar", "Selecionar" },
    { "Select Folder", "Elegir Carpeta", "Escolher Pasta" },
    { "Select Linked", "Seleccionar Vinculado", "Selecionar Vinculado" },
    { "Select Linked: click the", "Seleccionar Vinculado: clic sobre", "Selecionar Vinculado: clique sobre" },
    { "Select Mode", "Modo Selección", "Modo Seleção" },
    { "Select faces with more than 3 sides to triangulate", "Selecciona caras de más de 3 lados para triangular", "Selecione faces com mais de 3 lados para triangular" },
    { "Selected only", "Solo seleccionados", "Apenas selecionados" },
    { "Selection to Active", "Selección al activo", "Seleção para o ativo" },
    { "Selection to Cursor", "Selección a Cursor", "Seleção para Cursor" },
    { "Selection to Cursor (Keep Offset)", "Selección al cursor (mantener desfase)", "Seleção para o cursor (manter deslocamento)" },
    { "Selection to Grid", "Selección a la cuadrícula", "Seleção para a grade" },
    { "Set Active Camera: the active object is not a camera", "Cámara activa: el objeto activo no es una cámara", "Câmera ativa: o objeto ativo não é uma câmera" },
    { "Set Active Object as Camera", "Objeto Activo como Cámara", "Objeto Ativo como Câmera" },
    { "Set Keyframe Handle Type", "Definir Tipo de Manija", "Definir Tipo de Alça" },
    { "Set Origin", "Definir Origen", "Definir Origem" },
    { "Set Parent", "Emparentar", "Parentear" },
    { "Set Parent To", "Emparentar a", "Parentear Para" },
    { "Settings", "Ajustes", "Ajustes" },
    { "Settings saved", "Ajustes guardados", "Ajustes salvos" },
    { "Shade Flat", "Sombrear Plano", "Sombrear Plano" },
    { "Shade Smooth", "Sombrear Suave", "Sombrear Suave" },
    { "Shininess", "Dureza", "Brilho" },
    { "Shortest Path (Fill Region)", "Camino Más Corto (Rellenar Región)", "Caminho Mais Curto (Preencher Região)" },
    { "Shortest path selected", "Camino más corto seleccionado", "Caminho mais curto selecionado" },
    { "Shortest path: region filled", "Camino más corto: región rellenada", "Caminho mais curto: região preenchida" },
    { "Show Chrome UV", "Mostrar Chrome UV", "Mostrar Chrome UV" },
    { "Show Overlays", "Mostrar Superposiciones", "Mostrar Sobreposições" },
    { "Shrink/Fatten", "Encoger/Engrosar", "Encolher/Engrossar" },
    { "Simple", "Simple", "Simples" },
    { "Size", "Tamaño", "Tamanho" },
    { "Smart Euler", "Euler Inteligente", "Euler Inteligente" },
    { "Smart UV Project", "Proyección UV Inteligente", "Projeção UV Inteligente" },
    { "Smart UV Project: not implemented yet", "Proyección UV Inteligente: aún no implementado", "Projeção UV Inteligente: ainda não implementado" },
    { "Smooth", "Suave", "Suave" },
    { "Smooth Shading", "Sombreado Suave", "Sombreamento Suave" },
    { "Snap Base", "Base de Snap", "Base de Snap" },
    { "Snap Base:", "Base de Snap:", "Base de Snap:" },
    { "Snap Target", "Destino de Snap", "Destino de Snap" },
    { "Snap Target for Individual Elements", "Destino de Snap para elementos individuales", "Destino de Snap para elementos individuais" },
    { "Snap Target:", "Destino de Snap:", "Destino de Snap:" },
    { "Solid Preview", "Vista Sólido", "Prévia Sólido" },
    { "Specular", "Especular", "Especular" },
    { "Sphere Map (software)", "Mapa Esférico (software)", "Mapa Esférico (software)" },
    { "Sphere Projection", "Proyección de Esfera", "Projeção de Esfera" },
    { "Split Column", "Dividir Columna", "Dividir Coluna" },
    { "Split Row", "Dividir Fila", "Dividir Linha" },
    { "Spot Cutoff", "Ángulo Spot", "Ângulo Spot" },
    { "Spot Exponent", "Exponente Spot", "Expoente Spot" },
    { "Start", "Inicio", "Início" },
    { "Start:%d", "Inicio:%d", "Início:%d" },
    { "Statistics", "Estadísticas", "Estatísticas" },
    { "Steps Viewport", "Pasos Viewport", "Passos Viewport" },
    { "Stretch U", "Estirar U", "Esticar U" },
    { "Stretch V", "Estirar V", "Esticar V" },
    { "Subdivision Surface", "Superficie de Subdivisión", "Superfície de Subdivisão" },
    { "Summary", "Resumen", "Resumo" },
    { "Switch to 0-100%", "Cambiar a 0-100%", "Mudar para 0-100%" },
    { "Switch to 0-255", "Cambiar a 0-255", "Mudar para 0-255" },
    { "Sync Selection", "Sincronizar Selección", "Sincronizar Seleção" },
    { "Target", "Objetivo", "Alvo" },
    { "Texture", "Textura", "Textura" },
    { "Texture %d", "Textura %d", "Textura %d" },
    { "Texture Paint", "Pintura de Textura", "Pintura de Textura" },
    { "The default material can not be edited. Create a new material.", "El material por defecto no se puede editar. Crea un material nuevo.", "O material padrão não pode ser editado. Crie um novo material." },
    { "The file \"", "El archivo \"", "O arquivo \"" },
    { "Threshold", "Umbral", "Limiar" },
    { "Timeline", "Línea de Tiempo", "Linha do Tempo" },
    { "Times", "Tiempos", "Tempos" },
    { "Top", "Superior", "Superior" },
    { "Transform", "Transformar", "Transformar" },
    { "Transform Orientations", "Orientaciones de Transformación", "Orientações de Transformação" },
    { "Transform Pivot Point", "Punto de pivote", "Ponto pivô" },
    { "Translate", "Trasladar", "Transladar" },
    { "Translation", "Traslación", "Translação" },
    { "Transparent", "Transparente", "Transparente" },
    { "Triangulate Faces", "Triangular Caras", "Triangular Faces" },
    { "UV Editor", "Editor UV", "Editor UV" },
    { "UV Maps", "Mapas UV", "Mapas UV" },
    { "UV Sphere", "Esfera UV", "Esfera UV" },
    { "UV: projected from view", "UV: proyectadas desde vista", "UV: projetadas da vista" },
    { "UV: projected from view (bounds)", "UV: proyectadas desde vista (límites)", "UV: projetadas da vista (limites)" },
    { "UVSphere", "EsferaUV", "EsferaUV" },
    { "Unwrap", "Desplegar", "Desdobrar" },
    { "Unwrap: not implemented yet", "Desplegar: aún no implementado", "Desdobrar: ainda não implementado" },
    { "Value", "Valor", "Valor" },
    { "Value Y", "Valor Y", "Valor Y" },
    { "Vector", "Vector", "Vetor" },
    { "Vertex", "Vértice", "Vértice" },
    { "Vertex Animation", "Animación de Vértices", "Animação de Vértices" },
    { "Vertex Color", "Color de Vértice", "Cor de Vértice" },
    { "Vertex Groups", "Grupos de Vértices", "Grupos de Vértices" },
    { "Vertex Normal", "Normal de Vértice", "Normal de Vértice" },
    { "Vertex Paint", "Pintura de Vértices", "Pintura de Vértices" },
    { "Vertex groups optimized (1 bone/vertex)", "Grupos de vértices optimizados (1 hueso/vértice)", "Grupos de vértices otimizados (1 osso/vértice)" },
    { "Vertices", "Vértices", "Vértices" },
    { "View", "Vista", "Vista" },
    { "Viewpoint", "Punto de Vista", "Ponto de Vista" },
    { "Weight Paint", "Pintura de Pesos", "Pintura de Pesos" },
    { "Width", "Ancho", "Largura" },
    { "Wireframe Preview", "Vista Alámbrica", "Prévia Aramado" },
    { "X Axis", "Eje X", "Eixo X" },
    { "X Euler Rotation", "X Rotación Euler", "X Rotação Euler" },
    { "X Location", "X Posición", "X Posição" },
    { "X Scale", "X Escala", "X Escala" },
    { "X-Ray", "Rayos X", "Raio-X" },
    { "XYZ Euler", "Euler XYZ", "Euler XYZ" },
    { "Y Axis", "Eje Y", "Eixo Y" },
    { "Y Euler Rotation", "Y Rotación Euler", "Y Rotação Euler" },
    { "Y Location", "Y Posición", "Y Posição" },
    { "Y Scale", "Y Escala", "Y Escala" },
    { "Yes", "Sí", "Sim" },
    { "Z Euler Rotation", "Z Rotación Euler", "Z Rotação Euler" },
    { "Z Location", "Z Posición", "Z Posição" },
    { "Z Scale", "Z Escala", "Z Escala" },
    { "ZBuffer Preview", "Vista ZBuffer", "Prévia ZBuffer" },
    { "[X: time]", "[X: tiempo]", "[X: tempo]" },
    { "[Y: value]", "[Y: valor]", "[Y: valor]" },
    { "along", "en", "em" },
    { "center", "centro", "centro" },
    { "cube", "cubo", "cubo" },
    { "current frame", "frame actual", "frame atual" },
    { "cylinder", "cilindro", "cilindro" },
    { "deg", "grados", "graus" },
    { "edge", "arista", "aresta" },
    { "edge of a face", "arista de una cara", "aresta de uma face" },
    { "face", "cara", "face" },
    { "projection", "proyección", "projeção" },
    { "soon", "pronto", "em breve" },
    { "sphere", "esfera", "esfera" },
    { "vertex", "vértice", "vértice" },
    { "view", "vista", "vista" },
    { "you want to select (Esc to cancel)", "a seleccionar (Esc para cancelar)", "a selecionar (Esc para cancelar)" },
};

static const unsigned int W3D_LANG_ENTRADAS = sizeof(W3dLangTabla) / sizeof(W3dLangTabla[0]);

#endif
